pipeline{
agent{
docker{
image'maven:3.9.8-sapmachine-21'args'-v$HOME/.m2:/root/.m2'}

}

stages{
stage('build'){
steps{
echo'buildingworkerapp'dir('worker'){
sh'mvncompile'}

}

}

stage('test'){
steps{
echo'runningunittestsonworkerapp' dir('worker'){
sh'mvncleantest'}

}

}

stage('package'){
steps{
echo'packagingworkerappintoajarfile'dir('worker'){
sh'mvnpackage-DskipTests'archiveArtifactsartifacts:'**/target/*.jar',fingerprint:true}

}

}

stage('docker-package'){
agentanysteps{
echo'Packagingworkerappwithdocker'script{
docker.withRegistry('https://index.docker.io/v1/','dockerlogin'){
defworkerImage=docker.build("xxxxx/worker:v${
env.BUILD_ID}

","./worker")workerImage.push()workerImage.push("latest")}

}

}

}

}

post{
always{
echo'thejobiscomplete'}

}

}


